# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    application:
        name: url-shortner
    jackson:
        serialization.write_dates_as_timestamps: false
    mvc:
        favicon:
            enabled: false
    data:
        mongodb:
            host: localhost
            port: 27017
            database: url-shortner
    thymeleaf:
        cache: true
        mode: XHTML

# ===================================================================
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# Application specific properties
# ===================================================================
application:
    swagger:
        default-include-pattern: /api/.*
        title: URL Shortener API
        description: URL Shortener API Documentation
        version: 1.0.0